### ISSUE TITLE
Make the calls of the OSHtool assessment run in the background and not synchronously

### ISSUE THREAD

**Issue by puria** [interfacerproject/zenflows-osh#1]

**Comment by protodeniz** [comment]
Assuming we're talking about [losh-magic-import](https://github.com/interfacerproject/losh-magic-import), I believe it already allows you to do concurrent requests to the service without two separate requests blocking, meaning that a request could block on its own while we fetch and scan the repo, but they won't get affected by each other.  Isn't this a non-issue?

Or, do you want me to, like, create an API where we have ways to:
1. request to clone and scan a repo, and return an immediate result like "taken in operation" while we clone and scan the repo in the background;
2. request to get the readiness of  the "taken in operation" and possibility get back the result;
3. (optional) request to get cached data and ask for renewal, or automatically do this;

This can be implemented with a map modified at runtime, or with a small db like sqlite?

**Comment by puria** [comment]
Great! Thanks, that is good news.

So the requirement of what we want to achieve is:

I do run the import, and when some metadata are ready, that information are reflected into the interface (that means that the information is reflected also into zenflows).

I see two options here:
* after the osh job runned succesfully, the software calls directly zenflows to update the metadata of a EconomicResource. And in the meantime a semaphore will check if a job is undergoing, so to not allow user to overwrite info from the frontend, until the job finishes
* run the job and after is successful notify (via zenflows-inbox) the user/agent in the front end, and use the metadata gathered to update the information (manually approved) and reflect them to zenflows 

What do you think?

@phoebus-84 keep an eye to this to decide which reflects also less work in the FE

**Comment by protodeniz** [comment]
Hmm.  I didn't know we were gonna use this service like this.  I was just implementing something I thought was needed at that time (that is, take json input, reply json output).

From what I understand now, though, this service will be in contact with the FE, and the FE will ask it to clone and analyze a repo, right?

So, if my assumptions are correct, I believe this service shouldn't really be contacting with Zenflows directly, as it would need to have appropriate permissions from it.  Instead, I believe, this service should be used by the FE to query metadata and save to Zenflows itself, but this would put more work on FE.

If we want to reduce the work on the FE, though, I could do one of the suggested methods, although the first one sounds a bit tricky due to locking a record in the database for writing (updating).  I'll reply regarding this once I think more on this, and in the meanwhile, please tell me if my assumptions are right.

**Comment by puria** [comment]
Correct assumptions.
The idea is: already exists a repo elsewhere, you run the tool and collect some metadata, that are automagically filled inside the creation form (for the economicresource) to facilitate data injestion (README's, images, standard assessments, checks and lintings, readiness levels etc).

I do agree, and I prefer not to interact directly to the zenflows, and IMHO prefer to have human oversight over the process.

Yep, make your consideration, keep me updated ;)

**Comment by protodeniz** [comment]
Ah, clarifying that this is only done when creating the resource helped a lot.

In that case, the FE can just use the tool as it is right now.  I'll just improve the errors, and set up and instance.

Should we put this behind the GW (gateway) as well?  If so, please tell me to contact to Alberto or do yourself so regarding how to integrate this service with it (assuming the FE will query this service through the GW?).

**Comment by puria** [comment]
Yep inside the GW (although it's a proxy, actually) guess that was the rationale that @phoebus-84 used golang. Speak directly to @albertolerda for the deployment ;) /me not needed... take just care to document a little

**Comment by protodeniz** [comment]
Got it.

**Comment by protodeniz** [comment]
@albertolerda Should I incorporate the service directly into the GW, or should we make it another microservice and link it to the GW?

**Comment by phoebus-84** [comment]
GW, at present, it is merely a proxy, so I believe it would be better to create a separate service. I believe the tool could be useful for running the osh-tool on a repository, but then it is the responsibility of the interfacer-user to update the data in zenflows. The  losh-magic-import (maybe renamed) could also be useful, even without the interfacer-GUI, as a service for obtaining osh-tool checks and analysis from a URL

**Comment by albertolerda** [comment]
I confirm what Ennio said, for the moment `interfacer-gateway` is only a proxy and we have put all the services outside.

**Comment by albertolerda** [comment]
So I would add another service (e.g. `zenflows-losh-import`) and then add it to:
- the list of "proxied hosts" https://github.com/interfacerproject/interfacer-gateway/blob/e122bd2750ebe7eecc44bd5a568df6700fab8fd2/main.go#L41
- the docker compose deployment https://github.com/interfacerproject/interfacer-gateway/blob/main/devops/roles/proxy-docker-compose/templates/docker-compose.yml.j2

**Comment by protodeniz** [comment]
I think we got this covered.
